name: Validate Commit Messages

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  check-commit-messages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate commit messages
        run: |
          regex="^(ISSUE|STORY)-[0-9]+:"

          invalid=0
          for msg in $(git log ${{ github.event.before }}..${{ github.sha }} --pretty=format:%s); do
            if [[ ! $msg =~ $regex ]]; then
              echo "❌ Invalid commit message: $msg"
              invalid=1
            fi
          done

          if [[ $invalid -eq 1 ]]; then
            echo "❌ Commit message validation failed."
            exit 1

